export const IDEAS_LIST_REQUEST = 'IDEAS_LIST_REQUEST' ;
export const IDEAS_LIST_SUCCESS = 'IDEAS_LIST_SUCCESS' ;
export const IDEAS_LIST_FAIL = 'IDEAS_LIST_FAIL' ;

export const IDEAS_CREATE_REQUEST = 'IDEAS_CREATE_REQUEST' ;
export const IDEAS_CREATE_SUCCESS = 'IDEAS_CREATE_SUCCESS' ;
export const IDEAS_CREATE_FAIL = 'IDEAS_CREATE_FAIL' ;

export const IDEAS_UPDATE_REQUEST = 'IDEAS_UPDATE_REQUEST' ;
export const IDEAS_UPDATE_SUCCESS = 'IDEAS_UPDATE_SUCCESS' ;
export const IDEAS_UPDATE_FAIL = 'IDEAS_UPDATE_FAIL' ;

export const IDEAS_DELETE_REQUEST = 'IDEAS_DELETE_REQUEST' ;
export const IDEAS_DELETE_SUCCESS = 'IDEAS_DELETE_SUCCESS' ;
export const IDEAS_DELETE_FAIL = 'IDEAS_DELETE_FAIL' ;

